const MODEL_NAME = 'EventLog';
const TABLE_NAME = 'event_logs';

const TYPE = {
  LABEL_SIGNED_ARTIST: 'LABEL_SIGNED_ARTIST',
  LABEL_FIRED_ARTIST: 'LABEL_FIRED_ARTIST',
  LABEL_RENAMED: 'LABEL_RENAMED',
  ARTIST_NEW_SONG: 'ARTIST_NEW_SONG',
  ARTIST_NEW_ALBUM: 'ARTIST_NEW_ALBUM'
};

module.exports = {
  MODEL_NAME,
  TABLE_NAME,
  TYPE
};